# DOWNLOAD_PATH = "data/downloaded/"
DOWNLOAD_PATH = "/mnt/wdhdd4tb/Vessel_data/downloaded/"
CSV_PATH = "data/csv/"
PARQUET_PATH = "data/parquet/"
GDB_FILE_PATH = "data/gdb/"
GDB_EXTRACTED_FILE_PATH = "data/gdb_csv_geo/"
GDB_PARQUET_FILE_PATH = "data/gdb_parquet/"
OVERWRITE_DOWNLOAD = True
ZIP_DOWNLOAD = True
SKIP_DOWNLOAD = True
